
package autoGenerated;

import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "nom",
    "pr\u00e9nom",
    "date de naissance",
    "lieu de naissance"
})
public class Fondateur {

    @JsonProperty("nom")
    private String nom;
    @JsonProperty("pr\u00e9nom")
    private String prNom;
    @JsonProperty("date de naissance")
    private String dateDeNaissance;
    @JsonProperty("lieu de naissance")
    private LieuDeNaissance lieuDeNaissance;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("nom")
    public String getNom() {
        return nom;
    }

    @JsonProperty("nom")
    public void setNom(String nom) {
        this.nom = nom;
    }

    @JsonProperty("pr\u00e9nom")
    public String getPrNom() {
        return prNom;
    }

    @JsonProperty("pr\u00e9nom")
    public void setPrNom(String prNom) {
        this.prNom = prNom;
    }

    @JsonProperty("date de naissance")
    public String getDateDeNaissance() {
        return dateDeNaissance;
    }

    @JsonProperty("date de naissance")
    public void setDateDeNaissance(String dateDeNaissance) {
        this.dateDeNaissance = dateDeNaissance;
    }

    @JsonProperty("lieu de naissance")
    public LieuDeNaissance getLieuDeNaissance() {
        return lieuDeNaissance;
    }

    @JsonProperty("lieu de naissance")
    public void setLieuDeNaissance(LieuDeNaissance lieuDeNaissance) {
        this.lieuDeNaissance = lieuDeNaissance;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Fondateur.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("nom");
        sb.append('=');
        sb.append(((this.nom == null)?"<null>":this.nom));
        sb.append(',');
        sb.append("prNom");
        sb.append('=');
        sb.append(((this.prNom == null)?"<null>":this.prNom));
        sb.append(',');
        sb.append("dateDeNaissance");
        sb.append('=');
        sb.append(((this.dateDeNaissance == null)?"<null>":this.dateDeNaissance));
        sb.append(',');
        sb.append("lieuDeNaissance");
        sb.append('=');
        sb.append(((this.lieuDeNaissance == null)?"<null>":this.lieuDeNaissance));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.dateDeNaissance == null)? 0 :this.dateDeNaissance.hashCode()));
        result = ((result* 31)+((this.lieuDeNaissance == null)? 0 :this.lieuDeNaissance.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.nom == null)? 0 :this.nom.hashCode()));
        result = ((result* 31)+((this.prNom == null)? 0 :this.prNom.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Fondateur) == false) {
            return false;
        }
        Fondateur rhs = ((Fondateur) other);
        return ((((((this.dateDeNaissance == rhs.dateDeNaissance)||((this.dateDeNaissance!= null)&&this.dateDeNaissance.equals(rhs.dateDeNaissance)))&&((this.lieuDeNaissance == rhs.lieuDeNaissance)||((this.lieuDeNaissance!= null)&&this.lieuDeNaissance.equals(rhs.lieuDeNaissance))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.nom == rhs.nom)||((this.nom!= null)&&this.nom.equals(rhs.nom))))&&((this.prNom == rhs.prNom)||((this.prNom!= null)&&this.prNom.equals(rhs.prNom))));
    }

}
